name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
 
      - name: Install python
        run: uv python install

      - name: Install dependencies
        run: uv sync --frozen

      - name: Ruff format
        run: uvx ruff format src tests

      - name: Run tests 
        run: uv run -m pytest